services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techchallenge_backend
    restart: always
    ports:
      - '9090:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - techchallenge_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  db:
    image: postgres:16.2
    shm_size: 1g
    container_name: techchallenge_psql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0o9i8u7
      - POSTGRES_DB=techchallenge
    ports:
      - '5433:5432'
    volumes:
      - dbdata_techchallenge:/var/lib/postgresql/data
      - ./src/main/resources/db/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - techchallenge_net

volumes:
  dbdata_techchallenge:

networks:
  techchallenge_net:
    driver: bridge
#    external: true