apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: dGVjaGNoYWxsZW5nZV91c3I=
  DB_PASSWORD: UDBvOWk4dTc=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: UDBvOWk4dTc=